### ISSUE TITLE
`self` links within foreign relations don't resolve to the correct resources

### ISSUE THREAD

**Issue by futurist** [holidayextras/jsonapi-server#83] opened 2016-01-05 05:47 UTC
In the example folder, start `node server.js`, with `GET` below to foreign key `parent` of `tag` 

**A http://localhost:16006/rest/tags/?filter[parent]=6ec62f6d-9f82-40c5-b4f4-279ed1765492**
````
......
"data": {
        "id": "7541a4de-4986-4597-81b9-cf31b6762486",
        "type": "tags"  //this res.name == 'live', which is not direct children of 279ed1765492
    },
......
````

**B http://localhost:16006/rest/tags/relationships/?parent=6ec62f6d-9f82-40c5-b4f4-279ed1765492**
````
......
 "data": [{
            "type": "tags",
            "id": "2a3bdea4-a889-480d-b886-104498c86f69",
            "attributes": {
                "name": "staging"
            }
......
````

should A && B return same version of data? now the returned data of A seems not correctly.

**Comment by theninj4** [comment] 2016-01-06 21:08
Your first request:
http://localhost:16006/rest/tags/?filter[parent]=6ec62f6d-9f82-40c5-b4f4-279ed1765492
Gives you all `tags` who have a parent attribute/relation matching the above UUID. The tag with id `2a3bdea4-a889-480d-b886-104498c86f69` is the only resource matching that request within the example server, and it is correctly returned.

Your second request:
http://localhost:16006/rest/tags/relationships/?parent=6ec62f6d-9f82-40c5-b4f4-279ed1765492
is incorrectly identifying the resource.

It looks like a regression from #66 - This route isn't a part of the official spec, I originally created it when trying to make it easier to handle foreign relationships. Having now had first hand experience consuming a json:api service, I'm inclined to simply remove this route.

**Comment by theninj4** [comment] 2016-04-08 10:55
I'm going to close this one - it only effects the in-memory handler due to the simplistic implementation whereby it doesn't filter attributes (it relies on the post-processor to validate output).

**Closed by theninj4** 2016-04-08 10:55 UTC
Labels: bug
